# Extends the mainnet preset
CONFIG_NAME: "aerie"
PRESET_BASE: "mainnet"

# Transition
# ---------------------------------------------------------------
# Estimated on Sept 15, 2022
TERMINAL_TOTAL_DIFFICULTY: 0
# # By default, don't use these params
# TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
# TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# Genesis
# ---------------------------------------------------------------
# `2**14` (= 16,384)
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 4
# Dec 1, 2020, 12pm UTC
MIN_GENESIS_TIME: 0
# Mainnet initial fork version, recommend altering for testnets
GENESIS_FORK_VERSION: 0x20000000
# 604800 seconds (7 days)
GENESIS_DELAY: 100

# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair
ALTAIR_FORK_VERSION: 0x20000090
ALTAIR_FORK_EPOCH: 0
# Merge
BELLATRIX_FORK_VERSION: 0x20000091
BELLATRIX_FORK_EPOCH: 0 # Sept 6, 2022, 11:34:47am UTC
# Capella
CAPELLA_FORK_VERSION: 0x20000092
CAPELLA_FORK_EPOCH: 1 # April 12, 2023, 10:27:35pm UTC
# Time parameters
# ---------------------------------------------------------------
# 12 seconds
SECONDS_PER_SLOT: 8 #default 12
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 10
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256


# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 500000000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536

# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40

# Deposit contract
# ---------------------------------------------------------------
# Ethereum PoW Mainnet
DEPOSIT_CONTRACT_ADDRESS: 0x0000009f683783a040d39a235cae7bab6142bc1a
DEPOSIT_CHAIN_ID: 84886
DEPOSIT_NETWORK_ID: 84886

# Gwei values
# ---------------------------------------------------------------
MIN_DEPOSIT_AMOUNT: 10000000000000
# 2**5 * 10**9 (:  1,000,000,000,000,000) Gwei / 1,000,000 AER
MAX_EFFECTIVE_BALANCE: 1000000000000000
# 2**0 * 10**9 (:  1,000,000,000) Gwei / 1 AER
EFFECTIVE_BALANCE_INCREMENT: 1000000000

# AERIE SPECIFIC
BASE_REWARD_FACTOR: 128
BASE_REWARDS_PER_EPOCH: 8
# TIMING
EPOCHS_PER_ETH1_VOTING_PERIOD: 16 # WAS 64 EPOCH
ETH1_FOLLOW_DISTANCE: 1000 # 1K Block of ETH1