CONFIG_NAME: "aeriemainnet"
PRESET_BASE: "mainnet"

# Genesis
GENESIS_FORK_VERSION: 0x20000000
# GENESIS_FORK_VERSION: 0x20000089
#GENESIS_FORK_VERSION: 0x00000001

# Altair
# AT GENESIS
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# Merge
# START FROM GENESIS
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0

# CAPELLA
CAPELLA_FORK_EPOCH: 1
CAPELLA_FORK_VERSION: 0x20000092

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x0000009f683783a040d39a235cae7bab6142bc1a
DEPOSIT_CHAIN_ID: 84886
DEPOSIT_NETWORK_ID: 84886

MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 4

# Gwei values
# ---------------------------------------------------------------
# 2**0 * 10**9 (:  10,000,000,000,000) Gwei / 10,000 AER
MIN_DEPOSIT_AMOUNT: 10000000000000
# 2**5 * 10**9 (:  1,000,000,000,000,000) Gwei / 1,000,000 AER
MAX_EFFECTIVE_BALANCE: 1000000000000000
# 2**0 * 10**9 (:  1,000,000,000) Gwei / 1 AER
EFFECTIVE_BALANCE_INCREMENT: 1000000000
# IF GOES BELOW THIS THEN THE VALIDATOR WILL BE REJECTED , 500,000 AER
EJECTION_BALANCE: 500000000000000

# Time parameters
# ---------------------------------------------------------------
# 8 seconds
SECONDS_PER_SLOT: 8
SLOTS_PER_EPOCH: 4
#
# 10 Seconds per block
SECONDS_PER_ETH1_BLOCK: 10
# 2**8 (:  256) epochs 
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (:  256) epochs 
SHARD_COMMITTEE_PERIOD: 256
# HOW MANY BLOCKS THE DEPOSIT SHOULD EXIST BEFORE ELIGIBLE TO BECOME A VALIDATOR ~ Aprox 8Hrs
ETH1_FOLLOW_DISTANCE: 2880
# GENESIS DELAY
GENESIS_DELAY: 100

BASE_REWARD_FACTOR: 64

#LIGHTHOUSE
MIN_GENESIS_TIME: 0
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536
