global:
  scrape_interval: 12s

scrape_configs:
  - job_name: "docker_stats_exporter"
    metrics_path: /
    static_configs:
      - targets:
          - "172.20.0.4:9487"
          
  - job_name: "validator"
    static_configs:
      - targets: ["172.20.0.2:8082"]

  # Change into your beacon node ip address and corresponding Port     
  - job_name: "beacon node"
    static_configs:
      - targets: ["{changetoyoubeaconrip}:8080"]
